blog/urls.py
from django.urls import path
from django.contrib import admin

from .feeds import LatestPostsFeed
from .import views


app_name = 'blog'
urlpatterns = [
path('feed/',LatestPostsFeed(), name='post_feed'),
path('',views.post_list, name='post_list'),
path('tag/<slug:tag_slug>', views.post_list, name="post_list_by_tag"),
path('<int:post_id>/share/', views.post_share, name='post_share'),
# path('', views.PostListView.as_view(), name='post_list'),
path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail')
]

compliance_schedule/urls.py
from django.urls import path, re_path
from . import views
app_name="compliance_schedule"
urlpatterns = [
    path('addItem/', views.ItemView.as_view(), name='addItem'),
    path('viewCompliance/', views.ComplianceTableView.as_view(), name='viewCompliance'),
    path('update/<int:form_id>/', views.UpdateView.as_view(), name='updateCompliance'),
    path('addPolicy/', views.PolicyFormView.as_view(), name='addPolicy'),
    path('viewPolicy/', views.PolicyTableView.as_view(), name='viewPolicy'),
    path('updatePolicy/<int:form_id>/',views.UpdatePolicyView.as_view(), name='updatePolicy' )
]

compliance_schedule/models.py
from django.db import models
from forms.choices import RISK_OWNER_CHOICES, APPLICATION_CHOICES
from django.core.validators import MinValueValidator, MaxValueValidator
from forms.choices import BU_CHOICES
from django.contrib.auth.models import User
REGULATOR_CHOICES = (
    ('BPAY','BPAY'),
    ('APRA','APRA'),
    ('ASX','ASX'),
    ('ASIC','ASIC'),
    ('AUSTRAC','AUSTRAC'),
    ('WORKSAFE','WORKSAFE'),
    ('ATO','ATO'),
    ('WORKPLACE GENDER EQUALITY AGENCY','WORKPLACE GENDER EQUALITY AGENCY'),
    ("N/A","N/A")
)
STATUS_CHOICES = (
('DONE','DONE'),
('PENDING','PENDING'),
('OVERDUE','OVERDUE'),
)
class ScheduleItem(models.Model):
    RISK_OWNER_CHOICES = (
        ('Managing Director - GMY','Managing Director - GMY'),
        ('GM Banking & Wholesale','GM Banking & Wholesale'),
        ('GM Aggregation','GM Aggregation'),
        ('Group CFO','Group CFO'),
        ('Banking CFO / Company Sec','Banking CFO / Company Sec'),
        ('Chief Risk Officer','Chief Risk Officer'),
        ('Head of Technology and Operations','Head of Technology and Operations'),
        ('Managing Director - Finsure','Managing Director - Finsure'),
        ('Board','Board'),
        ('Compliance Officer - Finsure', 'Compliance Officer - Finsure'),
        ('Head of Operations - Betterchoice', 'Head of Operations - Betterchoice'),

    )
    def __str__(self):
        return "{}:{}".format(self.compliance_requirement, self.responsible)
    due_date = models.DateTimeField()
    compliance_requirement = models.CharField(max_length=100)
    regulator = models.CharField(max_length=300, choices = REGULATOR_CHOICES)
    document_or_activity = models.CharField(max_length=200)
    responsible = models.CharField(max_length=200,choices = RISK_OWNER_CHOICES)
    frequency = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(24)], help_text="0 to 24")
    business_unit = models.CharField(max_length=50, choices = BU_CHOICES)

    status = models.CharField(max_length=20, choices = STATUS_CHOICES, default='PENDING')
class CompletionDate(models.Model):
    class Meta:
        ordering = ['-completion_date']
    def __str__(self):
        return "{} {}".format(self.completion_date.date(), self.schedule_item)
    completion_date = models.DateTimeField(null=True)
    schedule_item = models.ForeignKey( ScheduleItem, on_delete = models.CASCADE, related_name = 'completion_dates')
    submitter = models.ForeignKey( User,
                                on_delete = models.CASCADE,
                                related_name = 'compliance_completion_dates')

class PolicyItem(models.Model):
    def __str__(self):
        return "{}_{}".format(self.policy_type, self.name)

    due_date = models.DateTimeField()
    policy_type = models.CharField(max_length=250)
    name =  models.CharField(max_length=250)
    regulators =  models.CharField(max_length=250)
    regulatory_guide =  models.CharField(max_length=250,blank = True)
    frequency = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(24)], help_text="0 to 24")

    status =  models.CharField(max_length=250, choices = STATUS_CHOICES)
    responsible = models.CharField(max_length=200,choices = RISK_OWNER_CHOICES)
    reviewer =  models.CharField(max_length=200,choices = RISK_OWNER_CHOICES)
    approval_body =  models.CharField(max_length=250, null = True, blank = True)
    application =  models.CharField(max_length=250, choices = APPLICATION_CHOICES)
    note =  models.TextField(blank = True)

class ReviewDate(models.Model):
    class Meta:
        ordering = ['-review_date']
    def __str__(self):
        return "{} {}".format(self.review_date.date(), self.policy_item)
    review_date = models.DateTimeField(null=True)
    policy_item = models.ForeignKey( PolicyItem, on_delete = models.CASCADE, related_name = 'review_dates')
    submitter = models.ForeignKey(User,on_delete = models.CASCADE, related_name = 'policy_reviewed_dates')


# Create your models here.

compliance_schedule/forms.py
from django import forms
from .models import ScheduleItem, PolicyItem

class DateInput(forms.DateInput):
    input_type = 'date'

class PolicyForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(PolicyForm, self).__init__(*args, **kwargs)
    class Meta:
        model = PolicyItem
        fields = '__all__'
        widgets = {
            'due_date': DateInput(),
        }

class ItemForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ItemForm, self).__init__(*args, **kwargs)
        # self.fields['expected_resolution_date'].required = False
# regulatory_requirement = models.CharField(max_length=100)
# regulator = models.CharField(max_length=20, choices = REGULATOR_CHOICES)
# document_or_activity = models.CharField(max_length=200)
# responsible = models.CharField(max_length=200,choices = RISK_OWNER_CHOICES)
# frequency = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(24)], help_text="0 to 24")
# due_date = models.DateTimeField()
    class Meta:
        model = ScheduleItem
        fields =(
        'business_unit',
        'compliance_requirement',
        'regulator',
        'document_or_activity',
        'responsible',
        'frequency',
        'due_date',
        )
        widgets = {
            'due_date': DateInput(),

        }
class UpdatePolicyForm(forms.ModelForm):
    review_date = forms.DateField(label="Review Date", widget=DateInput())
    def __init__(self, *args, **kwargs):
        super(UpdatePolicyForm, self).__init__(*args, **kwargs)
        for field in self.fields.keys():
            if field != "review_date" and field != "note":
                self.fields[field].disabled = True
    class Meta:
        model = PolicyItem
        fields = '__all__'
        widgets = {
            'review_date': DateInput(),
            'due_date':DateInput()
        }

class UpdateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(UpdateForm, self).__init__(*args, **kwargs)
        for field in self.fields.keys():
            if field != "completion_date":
                self.fields[field].disabled = True


    completion_date = forms.DateField(label="Completion Date", widget=DateInput())
    class Meta:
        model = ScheduleItem
        fields = '__all__'
        widgets = {
            'completion_date': DateInput(),
            'due_date':DateInput()

        }
    # can use def clean_<any field name> to clean the value or raise validation errors

compliance_schedule/views.py
from django.shortcuts import render, redirect
from .models import ScheduleItem, CompletionDate, PolicyItem, ReviewDate
from .forms import ItemForm, UpdateForm, PolicyForm, UpdatePolicyForm
from django.views import View
from monthdelta import monthdelta
from forms.views import BaseTableView
from dashboard.views import SharedNames

class UpdateView(View):
    template_path = "compliance_schedule/update.html"
    model = UpdateForm
    item = ScheduleItem
    date_model = CompletionDate

    def get(self, request, form_id):
        form = self.model(instance = self.item.objects.get(id=form_id))
        return render(request, self.template_path, {'submitted':False, 'form':form})
    def post(self, request, form_id):
        submitted = False
        instance =  self.item.objects.get(id=form_id)
        form = self.model(request.POST or None, instance = instance)
        if form.is_valid() and request.user.is_authenticated:
            completion_date = self.date_model()
            completion_date.completion_date = form.cleaned_data['completion_date']
            completion_date.submitter = request.user
            completion_date.schedule_item = instance
            completion_date.save()
            instance.status = "DONE"
            instance.due_date = completion_date.completion_date + monthdelta(instance.frequency)
            instance.save()
            # if temp_form.completion_date
            submitted = True
            request.method="GET"
            return redirect("compliance_schedule:viewCompliance")
        return render(request, self.template_path, {'submitted':submitted, 'form':form})

class UpdatePolicyView(UpdateView):
    model = UpdatePolicyForm
    item = PolicyItem
    date_model = ReviewDate
    def post(self, request, form_id):
        submitted = False
        instance =  self.item.objects.get(id=form_id)
        form = self.model(request.POST or None, instance = instance)
        if form.is_valid() and request.user.is_authenticated:
            review_date = self.date_model()
            review_date.review_date = form.cleaned_data['review_date']
            review_date.submitter = request.user
            review_date.policy_item = instance
            review_date.save()
            instance.status = "DONE"
            instance.due_date = review_date.review_date + monthdelta(instance.frequency)
            instance.save()
            submitted = True
            request.method="GET"
            return redirect("compliance_schedule:viewPolicy")
        return render(request, self.template_path, {'submitted':submitted, 'form':form})

class ItemView(View):
    template_path = "compliance_schedule/form.html"
    model = ItemForm
    title = "Compliance Schedule"
    def get(self, request):
        submitted = False
        form = self.model()
        context =  {"submitted":submitted,"form":form, 'title':self.title}
        return render(request,self.template_path, context)
    def post(self, request):
        submitted = False
        form = self.model(request.POST)
        if form.is_valid() and request.user.is_authenticated:
            temp_form = form.save(commit=False)
            temp_form.save()
            submitted = True
            request.method="GET"
        context =  {"submitted":submitted,"form":form, 'title':self.title}
        return render(request,self.template_path, context)
class PolicyFormView(ItemView):
    model = PolicyForm
    title = "Policy Review Schedule"

class ComplianceTableView(BaseTableView):
    template_path = "compliance_schedule/compliance_schedule_table.html"
    model_names = [SharedNames.compliance_schedule_item]
    def _get_table_config(self):
        config = {}
        config[SharedNames.compliance_schedule_item.replace(' ','_').lower()] = {
        'visible_indices':[
            'due_date',
            'last_completion_date',
            'status',
            'compliance_requirement',
            'regulator',
            'responsible',
            'frequency',
            'action'
            ]}
        return config
class PolicyTableView(BaseTableView):
    template_path = "compliance_schedule/policy_review_table.html"
    model_names = [SharedNames.policy_review_item]
    def _get_table_config(self):
        config = {}
        config[SharedNames.policy_review_item.replace(' ','_').lower()] = {
        'visible_indices':[
            'due_date',
            'last_review_date',
            'status',
            'policy_type',
            'name',
            'application',
            'responsible',
            'frequency',
            'action'
            ]}
        return config

compliance_schedule/templates/compliance_schedule/compliance_schedule_table.html
{% extends "forms/table_base.html" %}
{% load humanize %}
{% load datediff %}
{% load prettyHeader %}
{% load lastCompleted %}

{% block tables %}
<div class="row">
  {% for table in data %}
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2> {{ table.name }} </h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <table id="{{ table.id }}" class="table table-striped table-bordered" width="100%">
          <thead>
            <tr>

                {% for field, value in table.data.0.fields.items %}
                  <th class="{{ field }}">{{ field|prettyHeader }}</th>
                  {% endfor %}

                  <th class="last_completion_date">Last Completion Date</th>
                  <th class="action">Action</th>
            </tr>
          </thead>
          <tbody>
            {% for instance in table.data %}
              <tr>
                {% for field, value in instance.fields.items %}
                  {% if "date" in field %}
                    <td>{{ value|date:"Y-m-d"}}</td>
                  {% elif "amount" in field or "loss" in field %}
                    <td>{{ value|floatformat:"0"|intcomma }}</td>
                  {% elif value == "DONE" %}
                  <td><i class="green">{{ value }}</i></td>
                  {% elif value == "PENDING" %}
                  <td><i class="blue">{{ value }}</i></td>
                  {% elif value == "OVERDUE" %}
                  <td><i class="red">{{ value }}</i></td>
                  {% else %}
                  <td> {{value}} </td>
                  {% endif %}
                {% endfor %}


                <td>
                    {{ instance.pk|lastCompleted|date:"Y-m-d"  }}
                </td>
                <td><a href="{% url "compliance_schedule:updateCompliance" form_id=instance.pk %}"><strong>Edit</strong></a></td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
  {% endfor %}

</div>
{% endblock %}




                    <td>
                      {% if item.status == "DONE" %}
                      <i class="green">{{ item.status }}</i>
                      {% elif item.status == "PENDING" %}
                      <i class="blue">{{ item.status }}</i>
                      {% else %}
                      <i class="red">{{ item.status }}</i>
                      {% endif %}


                    </td>

compliance_schedule/templates/compliance_schedule/email.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>BNK Support: Overdue {{ title }} Item</title>


  </head>
  <body style="-webkit-text-size-adjust: none; box-sizing: border-box; color: #74787E; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; height: 100%; line-height: 1.4; margin: 0; width: 100% !important;" bgcolor="#F2F4F6">
  <style type="text/css">
    body {
    width: 100% !important; height: 100%; margin: 0; line-height: 1.4; background-color: #F2F4F6; color: #74787E; -webkit-text-size-adjust: none;
    }
    @media only screen and (max-width: 600px) {
      .email-body_inner {
        width: 100% !important;
      }
      .email-footer {
        width: 100% !important;
      }
    }
    @media only screen and (max-width: 500px) {
      .button {
        width: 100% !important;
      }
    }
  </style>
    <span class="preheader" style="box-sizing: border-box; display: none !important; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 1px; line-height: 1px; max-height: 0; max-width: 0; mso-hide: all; opacity: 0; overflow: hidden; visibility: hidden;">Overdue {{ title }} Items</span>
    <table class="email-wrapper" width="100%" cellpadding="0" cellspacing="0" style="box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; margin: 0; padding: 0; width: 100%;" bgcolor="#F2F4F6">
    <tr>
        <td align="center" style="box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; word-break: break-word;">
          <table class="email-content" width="100%" cellpadding="0" cellspacing="0" style="box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; margin: 0; padding: 0; width: 100%;">
            <tr>
              <td class="email-masthead" style="box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding: 25px 0; word-break: break-word;" align="center">
                <a href="https://example.com" class="email-masthead_name" style="box-sizing: border-box; color: #bbbfc3; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 16px; font-weight: bold; text-decoration: none; text-shadow: 0 1px 0 white;">
                 BNK Support
                </a>
              </td>
            </tr>

            <tr>
              <td class="email-body" width="100%" cellpadding="0" cellspacing="0" style="-premailer-cellpadding: 0; -premailer-cellspacing: 0; border-bottom-color: #EDEFF2; border-bottom-style: solid; border-bottom-width: 1px; border-top-color: #EDEFF2; border-top-style: solid; border-top-width: 1px; box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; margin: 0; padding: 0; width: 100%; word-break: break-word;" bgcolor="#FFFFFF">
                <table class="email-body_inner" align="center" width="570" cellpadding="0" cellspacing="0" style="box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; margin: 0 auto; padding: 0; width: 570px;" bgcolor="#FFFFFF">

                    <tr>
                        <td class="content-cell" style="box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding: 35px; word-break: break-word;">
                          <h1 style="box-sizing: border-box; color: #2F3133; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 19px; font-weight: bold; margin-top: 0;" align="left">Hi,</h1>
                        <p style="box-sizing: border-box; color: #74787E; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 16px; line-height: 1.5em; margin-top: 0;" align="left">{{ title }} items listed below are overdue. Please login to https://bnk.support to address them ASAP. </p>

                        </td>
                    </tr>
                    <tr>

                        <td class="content-cell" style="box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding: 35px; word-break: break-word;">


                            {% if title == "Compliance Schedule" %}

                              {% for field in form %}

                                <h1 style="box-sizing: border-box; color: #74787E; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 16px; line-height: 1.5em; margin-top: 0;" align="left">Item: {{ field.regulatory_requirement}} </h1>
                                <h1 style="box-sizing: border-box; color: #74787E; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 16px; line-height: 1.5em; margin-top: 0;" align="left">Due: {{ field.due_date|date:"Y-m-d"  }} </h1>
                                  <br/>
                              {% endfor %}
                            {% else %}
                              {% for field in form %}

                                <h1 style="box-sizing: border-box; color: #74787E; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 16px; line-height: 1.5em; margin-top: 0;" align="left">Item: {{ field.name}} </h1>
                                <h1 style="box-sizing: border-box; color: #74787E; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 16px; line-height: 1.5em; margin-top: 0;" align="left">Due: {{ field.due_date|date:"Y-m-d"  }} </h1>
                                <br/>
                              {% endfor %}
                            {% endif %}






                        </td>

                    </tr>
                    <tr>

                        <td class="content-cell" style="box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding: 35px; word-break: break-word;">


                        <p style="box-sizing: border-box; color: #74787E; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 16px; line-height: 1.5em; margin-top: 0;" align="left">If you did not subscribe to this, please ignore this email or <a href="mailto:warren.cheng@goldfieldsmoney.com.au" style="box-sizing: border-box; color: #3869D4; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif;">contact support</a> if you have questions.</p>
                        <p style="box-sizing: border-box; color: #74787E; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 16px; line-height: 1.5em; margin-top: 0;" align="left">Thanks,
                        <br />The BNK Support Team</p>






                        </td>
                    </tr>
                </table>




              </td>
            </tr>
            </table>
        </td>
    </tr>
    <tr>
      <td style="box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; word-break: break-word;">
        <table class="email-footer" align="center" width="570" cellpadding="0" cellspacing="0" style="box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; margin: 0 auto; padding: 0; text-align: center; width: 570px;">
          <tr>
            <td class="content-cell" align="center" style="box-sizing: border-box; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; padding: 35px; word-break: break-word;">
              <p class="sub align-center" style="box-sizing: border-box; color: #AEAEAE; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 12px; line-height: 1.5em; margin-top: 0;" align="center">© 2019 BNK Banking Corp. Ltd. All rights reserved.</p>
              <p class="sub align-center" style="box-sizing: border-box; color: #AEAEAE; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 12px; line-height: 1.5em; margin-top: 0;" align="center">
                BNK Banking Corporation Ltd
                <br />Level 14, 191 St Georges Terrace, Perth 6000, WA, Australia

              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    </table>



</body>
</html>

compliance_schedule/templates/compliance_schedule/form.html
{% extends "dashboard/base_site.html" %}
{% load widget_tweaks %}
{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>BNK {{ title }}</h3>
        </div>


      </div>
      <div class="clearfix"></div>
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2>{{ title }} Item Addition</h2>
              <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            {% if submitted %}
              <div class="x_content">
                  <p>The item has been added successfully!</p>
              </div>
            {% else %}
            <div class="x_content">
              <small>FIELDS WITH A STAR (*) ARE REQUIRED</small>
              <br />
              <form id="demo-form2" action="." method="POST" data-parsley-validate class="form-horizontal form-label-left">

                {% for field in form %}

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">{{ field.label }}
                      {% if field.field.required %}
                      <span class="required">*</span>
                      {% endif %}
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                         {% render_field field class+="form-control col-md-7 col-xs-12" placeholder=field.help_text %}

                    </div>
                    {{ field.errors }}
                </div>

                {% endfor %}
                {% csrf_token %}

                <div class="ln_solid"></div>
                <div class="form-group">
                  <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">

  		              <button class="btn btn-primary" type="reset">Reset</button>
                    <button type="submit" class="btn btn-success">Submit</button>
                  </div>
                </div>

              </form>
            </div>
            {% endif %}
          </div>
        </div>
      </div>

    </div>
  </div>

{% endblock content %}
{% block custom_js%}
{% endblock custom_js%}

compliance_schedule/templates/compliance_schedule/policy_review_table.html
{% extends "forms/table_base.html" %}
{% load humanize %}
{% load datediff %}
{% load prettyHeader %}
{% load lastReviewed %}

{% block tables %}
<div class="row">
  {% for table in data %}
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2> {{ table.name }} </h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <table id="{{ table.id }}" class="table table-striped table-bordered" width="100%">
          <thead>
            <tr>

                {% for field, value in table.data.0.fields.items %}
                  <th class="{{ field }}">{{ field|prettyHeader }}</th>
                  {% endfor %}

                  <th class="last_review_date">Last Review Date</th>
                  <th class="action">Action</th>
            </tr>
          </thead>
          <tbody>
            {% for instance in table.data %}
              <tr>
                {% for field, value in instance.fields.items %}
                  {% if "date" in field %}
                    <td>{{ value|date:"Y-m-d"}}</td>
                  {% elif "amount" in field or "loss" in field %}
                    <td>{{ value|floatformat:"0"|intcomma }}</td>
                  {% elif value == "DONE" %}
                  <td><i class="green">{{ value }}</i></td>
                  {% elif value == "PENDING" %}
                  <td><i class="blue">{{ value }}</i></td>
                  {% elif value == "OVERDUE" %}
                  <td><i class="red">{{ value }}</i></td>
                  {% else %}
                  <td> {{value}} </td>
                  {% endif %}
                {% endfor %}


                <td>
                    {{ instance.pk|lastReviewed|date:"Y-m-d"  }}
                </td>
                <td><a href="{% url "compliance_schedule:updatePolicy" form_id=instance.pk %}"><strong>Edit</strong></a></td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
  {% endfor %}

</div>
{% endblock %}




                    <td>
                      {% if item.status == "DONE" %}
                      <i class="green">{{ item.status }}</i>
                      {% elif item.status == "PENDING" %}
                      <i class="blue">{{ item.status }}</i>
                      {% else %}
                      <i class="red">{{ item.status }}</i>
                      {% endif %}


                    </td>

compliance_schedule/templates/compliance_schedule/update.html
{% extends "dashboard/base_site.html" %}
{% load widget_tweaks %}
{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>BNK Compliance Schedule</h3>
        </div>


      </div>
      <div class="clearfix"></div>
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2>Compliance Schedule Item Addition</h2>
              <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            {% if submitted %}
              <div class="x_content">
                  <p>The item has been added successfully!</p>
              </div>
            {% else %}
            <div class="x_content">
              <small>FIELDS WITH A STAR (*) ARE REQUIRED</small>
              <br />
              <form id="demo-form2" action="." method="POST" data-parsley-validate class="form-horizontal form-label-left">

                {% for field in form %}

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">{{ field.label }}
                      {% if field.field.required %}
                      <span class="required">*</span>
                      {% endif %}
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                         {% render_field field class+="form-control col-md-7 col-xs-12" placeholder=field.help_text %}
                    </div>
                    {{ field.errors }}
                </div>

                {% endfor %}
                {% csrf_token %}

                <div class="ln_solid"></div>
                <div class="form-group">
                  <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">

  		              <button class="btn btn-primary" type="reset">Reset</button>
                    <button type="submit" class="btn btn-success">Submit</button>
                  </div>
                </div>

              </form>
            </div>
            {% endif %}
          </div>
        </div>
      </div>

    </div>
  </div>

{% endblock content %}
{% block custom_js%}
<script>

</script>
{% endblock custom_js%}