blog/urls.py
from django.urls import path
from django.contrib import admin

from .feeds import LatestPostsFeed
from .import views


app_name = 'blog'
urlpatterns = [
path('feed/',LatestPostsFeed(), name='post_feed'),
path('',views.post_list, name='post_list'),
path('tag/<slug:tag_slug>', views.post_list, name="post_list_by_tag"),
path('<int:post_id>/share/', views.post_share, name='post_share'),
# path('', views.PostListView.as_view(), name='post_list'),
path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail')
]

compliance_schedule/urls.py
from django.urls import path, re_path
from . import views
app_name="compliance_schedule"
urlpatterns = [
    path('addItem/', views.ItemView.as_view(), name='addItem'),
    path('viewCompliance/', views.ComplianceTableView.as_view(), name='viewCompliance'),
    path('update/<int:form_id>/', views.UpdateView.as_view(), name='updateCompliance'),
    path('addPolicy/', views.PolicyFormView.as_view(), name='addPolicy'),
    path('viewPolicy/', views.PolicyTableView.as_view(), name='viewPolicy'),
    path('updatePolicy/<int:form_id>/',views.UpdatePolicyView.as_view(), name='updatePolicy' )
]

dashboard/urls.py
from django.urls import path, re_path
from . import views
app_name="dashboard"
urlpatterns = [
    # Matches any html file - to be used for gentella
    # Avoid using your .html in your resources.
    # Or create a separate django app.
#    re_path(r'^.*\.html', views.gentella_html, name='gentella'),

    # The home page

    path('', views.index, name='index'),
    
    path('incident/', views.incident, name="incident"),
    path('complaint/', views.complaint, name="complaint")

]

forms/urls.py
from django.urls import path
from django.contrib import admin
from .import views

app_name = 'forms'
urlpatterns = [

    path('review/', views.SubmissionTableView.as_view(), name='review'),
    path('review/risk_factors', views.RiskFactorTableView.as_view(), name='risk_factor_review'),
    path('review/risk_controls', views.RiskFactorTableView.as_view(), name='risk_control_review'),
    path('submit/<slug:form_name>/',views.DefaultFormView.as_view(), name='display_form'),
    path('submit/<slug:form_name>/wizard/', views.WizardFormView.as_view(), name='display_wizard'),
    path('edit/<slug:form_name>/<int:form_id>/', views.EditFormView.as_view(), name="edit"),
    path('editWizard/<slug:form_name>/<slug:form_id>/', views.EditWizardView.as_view(),name = 'editWizard'),
    path('add/<slug:form_name>/', views.RiskFactorAddView.as_view(), name='addRiskFactor'),
    path('edit_risk_factor/<slug:form_name>/<slug:form_id>/', views.RiskFactorEditView.as_view(), name="editRiskFactor"),

]

dashboard/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone

class PotentialLoss(models.Model):
    def __str__(self):
        return "{}".format(self.data_date)
    data_date = models.DateTimeField(default = timezone.now)
    Banking = models.FloatField(validators=[MinValueValidator(0)])
    Wholesale = models.FloatField(validators=[MinValueValidator(0)])
    Aggregation = models.FloatField(validators=[MinValueValidator(0)])

dashboard/views.py
from django.shortcuts import render, redirect
from django.db import models
from django.db.models import Func, F, Sum, Count, Q
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from forms.models import *
from datetime import timedelta
from monthdelta import monthdelta
from operator import itemgetter
import json
from compliance_schedule.models import PolicyItem, ScheduleItem
####Helper functions, and classes
class SharedNames:
	label_business_unit = "business_unit"
	fraud = "Fraud"
	incident = "Breach and Incident"
	hindsight = "Hindsight Review"
	complaint = "Complaint and Dispute"
	banking = "Banking"
	risk_control = "Risk Control"
	risk_factor_add = "Risk Factor Add"
	risk_factor_edit = "Risk Factor Edit"
	wholesale = "Wholesale"
	aggregation = "Aggregation"
	compliance_schedule_item = "Compliance Schedule Item"
	policy_review_item = "Policy Schedule Item"

	all_names = [fraud, incident, hindsight, complaint]
	models = {
	    fraud:Fraud,
	    incident:Incident,
	    complaint:Complaint,
		hindsight:Hindsight,
		risk_control:RiskControl,
		risk_factor_add:RiskFactor,
		risk_factor_edit:RiskFactor,
		compliance_schedule_item:ScheduleItem,
		policy_review_item :PolicyItem
	}
	heatmap_ids = {
	    fraud:"{}_heatmap".format(fraud),
	    incident:"{}_heatmap".format(incident),
	    complaint:"{}_heatmap".format(complaint),
	    hindsight:"{}_heatmap".format(hindsight),
	}
	full_names = {
	    fraud:"Frauds",
	    incident:"Breaches & Incidents",
	    complaint:"Complaints & Disputes",
	    hindsight: "Hindsight Reviews"
	}
	business_units = [
	    banking, wholesale, aggregation
	]
class Month(Func):
	function = "EXTRACT"
	template = "%(function)s(MONTH from %(expressions)s)"
	output_field = models.IntegerField()

class Year(Func):
	function = "EXTRACT"
	template = "%(function)s(YEAR from %(expressions)s)"
	output_field = models.IntegerField()



def get_12m_fraud_amounts():
	fraud_amounts=  {'date':[], 'loss':[]}
	for i in range(24):
		filt = {
		'discovery_date__gte':timezone.now() + monthdelta(-1-i),
		'discovery_date__lte':timezone.now() + monthdelta(-1*i),
		}
		loss = Fraud.objects.filter(**filt).values('transaction_amount').aggregate(amounts=Sum(F('transaction_amount')))['amounts']
		fraud_amounts['date'].append(str(timezone.now().date() + monthdelta(-1*i)))
		fraud_amounts['loss'].append(loss if loss else 0)
	return fraud_amounts

def get_12m_rolling(bu,item):

	complaint_losses = {"date":[],"loss":[]}
	incident_losses = {"date":[],"loss":[]}

	for i in range(24):
		filt = {
		'discovery_date__gte':timezone.now() + monthdelta(-12-i),
		'discovery_date__lte':timezone.now() + monthdelta(-1*i),
		'business_unit':bu
		}
		if item=="loss_incurred":
			filt = {
			'loss_incurred_date__gte':timezone.now() + monthdelta(-12-i),
			'loss_incurred_date__lte':timezone.now() + monthdelta(-1*i),
			'business_unit':bu
			}

		loss = Complaint.objects.filter(**filt).values(
				"business_unit",
				item,
				).aggregate(
					total_loss=Sum(
								F(item)
							)
				)["total_loss"]
		complaint_losses['date'].append(str(timezone.now().date() + monthdelta(-1*i)))
		complaint_losses['loss'].append(loss if loss else 0)
	for i in range(24):
		filt = {
		'discovery_date__gte':timezone.now() + monthdelta(-12-i),
		'discovery_date__lte':timezone.now() + monthdelta(-1*i),
		'business_unit':bu
		}
		if item=="loss_incurred":
			filt = {
			'loss_incurred_date__gte':timezone.now() + monthdelta(-12-i),
			'loss_incurred_date__lte':timezone.now() + monthdelta(-1*i),
			'business_unit':bu
			}
		loss = Incident.objects.filter(**filt).values(
				"business_unit",
				item,
				).aggregate(
					total_loss=Sum(
								F(item)
							)
				)["total_loss"]
		incident_losses['date'].append(str(timezone.now().date() + monthdelta(-1*i)))
		incident_losses['loss'].append(loss if loss else 0)

	for index, loss in enumerate(complaint_losses['loss']):
		incident_losses['loss'][index] += loss
	return incident_losses
def get_fraud_related_losses(bu):
	substrings=  ["fraud","paywave"]
	condition = Q(root_cause__icontains=substrings[0]) | Q(root_cause__icontains=substrings[1])


	item = "loss_incurred"
	complaint_losses = {"date":[],"loss":[]}
	incident_losses = {"date":[],"loss":[]}
	for i in range(24):
		loss = Complaint.objects.filter(
			loss_incurred_date__gte=timezone.now() + monthdelta(-12-i),
			loss_incurred_date__lte=timezone.now() + monthdelta(-1*i),
			business_unit=bu
		).filter(condition).values(
				"business_unit",
				item,

				).aggregate(
					total_loss=Sum(
								F(item)
							)
				)["total_loss"]
		complaint_losses['date'].append(str(timezone.now().date() + monthdelta(-1*i)))
		complaint_losses['loss'].append(loss if loss else 0)
	for i in range(24):
		loss = Incident.objects.filter(
			loss_incurred_date__gte=timezone.now() + monthdelta(-12-i),
			loss_incurred_date__lte=timezone.now() + monthdelta(-1*i),
			business_unit=bu
		).filter(condition).values(
				"business_unit",
				item,

				).aggregate(
					total_loss=Sum(
								F(item)
							)
				)["total_loss"]
		incident_losses['date'].append(str(timezone.now().date() + monthdelta(-1*i)))
		incident_losses['loss'].append(loss if loss else 0)

	for index, loss in enumerate(complaint_losses['loss']):
		incident_losses['loss'][index] += loss
	return incident_losses
"""
Dashbaord Top Item Data:
[
	[
	<major_name:str>,
	<major_number:int/float>,
	<minor_name:str>,
	<minor_number:int/float>,
	]

]
"""
class DashboardTopItem:
	def __init__(self, model_name ,filters = {}):
		self.model = SharedNames.models[model_name]
		self.filter = filters
	@property
	def first_day_of_this_year(self):
	    return timezone.now().replace(month=1, day=1)
	@property
	def first_day_of_last_year(self):
	    return self.first_day_of_this_year + monthdelta(-12)
	@property
	def first_day_of_this_month(self):
	    return timezone.now().replace(day=1)
	@property
	def first_day_of_last_month(self):
		return self.first_day_of_this_month + monthdelta(-1)
	def x_year_ago(self, x):
	    return timezone.now().replace(year=timezone.now().year-x)
	def _get_count(self, after):
	    try:
	        return self.model.objects.filter(discovery_date__gte=after, **self.filter).count()
	    except:
	        return self.model.objects.filter(submitted_date__gte=after, **self.filter).count()

	def _get_sum(self, after, field_name):
		if field_name == "loss_incurred":
			filt = {
			'loss_incurred_date__gte':after
			}
		else:
			filt = {
			'discovery_date__gte':after
			}

		try:
		    total = self.model.objects.filter(**filt, **self.filter).aggregate(total = Sum(field_name))["total"]
		except:
		    total = self.model.objects.filter(submitted_date__gte=after, **self.filter).aggregate(total = Sum(field_name))["total"]

		if total:
		    return int(total)
		else:
		    return 0
	def get_count_between(self, start_date, end_date):
	    return self._get_count(after=start_date) - self._get_count(after=end_date)
	def get_sum_between(self, start_date, end_date, field_name):
	    return self._get_sum(after=start_date, field_name = field_name) -\
	            self._get_sum(after=end_date, field_name = field_name)
	def get_data_between(self, start_date, end_date, data_type="count",field_name = None):
		if data_type =="count":
			return self.get_count_between(start_date, end_date)
		else:
			return self.get_sum_between(start_date, end_date, field_name)

"""
StackedBarchart Data = {
	<str:lable>:{
		<str:business_unit_1>:<int:count>,
		<str:business_unit_2>: <int:count>,
		<str:business_unit_3>: <int:count>,
	},



}
"""
class StackedBarChart:
	def __init__(self, model_name, count_field=None, sum_field=None, sum_by_field=None):
		self.model = SharedNames.models[model_name]
		self.stacked_field = "business_unit"
		self.count_field = count_field
		self.sum_field = sum_field
		self.sum_by_field = sum_by_field
	def get_top_ten_count_field(self):
		data = list(self.model.objects.values(self.count_field).annotate(count=Count(self.count_field)).order_by('-count'))
		if len(data) > 10:
			return [x[self.count_field] for x in data[:10]]
		else:
			return [x[self.count_field] for x in data]
	def get_count_field_by_stacked_field(self):
		return list(self.model.objects.values(self.count_field,self.stacked_field).annotate(count=Count(self.count_field)).order_by("-count"))
	def get_top_ten_sum_field_by(self):
		result = {}
		filter= {"{}__gt".format(self.sum_field):0}
		for i in self.model.objects.filter(**filter).values(self.sum_field,self.sum_by_field):
			sum_by_field = i[self.sum_by_field]
			sum_field = i[self.sum_field]
			if sum_by_field in result:
				result[sum_by_field] += sum_field
			else:
				result[sum_by_field]= sum_field
		sorted_result = sorted(result.items(), key = lambda kv:kv[1], reverse=True)


		if len(sorted_result) > 10:
			return [x[0] for x in sorted_result[:10]]
		else:
			return [x[0] for x in sorted_result]
	def get_count_data(self):
		data = []
		for item in self.get_top_ten_count_field():


			sub_dict = {}
			for bu in SharedNames.business_units:
				filter = {self.count_field:item, self.stacked_field:bu}
				sub_dict[bu]=self.model.objects.filter(**filter).count()
			if self.count_field == "risk_factor":
				item = RiskFactor.objects.get(id=item).name
			data.append([item,sub_dict])
		return data
	def get_sum_data(self):
		data = []
		for item in self.get_top_ten_sum_field_by():
			sub_dict = {}
			for bu in SharedNames.business_units:
				filter = {self.sum_by_field:item, self.stacked_field:bu, "{}__gt".format(self.sum_field):0}
				sub_dict[bu]=self.model.objects.filter(**filter).aggregate(sum=Sum(self.sum_field))['sum']
				if not sub_dict[bu]:
					sub_dict[bu]=0
				else:
					sub_dict[bu] = round(sub_dict[bu],0)
			data.append([item,sub_dict])
		return data

"""
Barchart Data = {
	<str:business_unit_1>:[
		[<str:label_1>, <int:count>],
		[<str:label_2>, <int:count>],
		...
	],
	<str:business_unit_2>:[
		[<str:label_1>, <int:count>],

dashboard/templates/dashboard/base_site.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block head %}
      {% block meta %}
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" href="/static/images/bnk.png" />
      {% endblock meta %}

      <title>BNK</title>

      {% block stylesheets %}
        <!-- Bootstrap -->
        <link href="/static/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="/static/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
        <!-- NProgress -->
        <link href="/static/vendors/nprogress/nprogress.css" rel="stylesheet">
        <!-- bootstrap-daterangepicker -->
        <link href="/static/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
        <!-- iCheck -->
        <link href="/static/vendors/iCheck/skins/flat/green.css" rel="stylesheet">
        <!-- bootstrap-progressbar -->
        <link href="/static/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
        <!-- JQVMap -->
        <link href="/static/vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet"/>
      {% endblock stylesheets %}
      <!-- Custom Theme Style -->
      <link href="/static/build/css/custom.css" rel="stylesheet">
    {% endblock head %}
  </head>

  <body class="{% block body_class %}nav-md {% endblock body_class %}">
    {% block body %}
      <div class="container body">
        <div class="main_container">

          {% block sidebar %}
            <div class="col-md-3 left_col menu_fixed">
              {% include "dashboard/sidebar.html" %}
            </div>
          {% endblock sidebar %}

          {% block top_navigation %}
            <div class="top_nav">
              {% include "dashboard/top_navigation.html" %}
            </div>
          {% endblock top_navigation %}
          {% if request.user.is_authenticated %}
          {% block content %}
            <!-- {{ content }} -->
          {% endblock content %}
          {% else %}
            <div class="right_col" role="main" style="height:70vh;">
                <p>You are not logged in. Click <a href="{% url "login" %}">here</a> to login.</p>
            </div>

          {% endif %}

          {% block footer %}
            <span>.</span>
          {% endblock footer %}
        </div>
      </div>

      {% block javascripts %}
        <script>
        var bu_color = {
            "Banking":"rgba(26,187,156,0.8)",
            "Wholesale":"rgba(231,76,60,0.8)",
            "Aggregation":"rgba(52,152,219,0.8)"
        };
        </script>
        <!-- jQuery -->
        <script src="/static/vendors/jquery/dist/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="/static/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- FastClick -->
        <script src="/static/vendors/fastclick/js/fastclick.js"></script>
        <!-- NProgress -->
        <script src="/static/vendors/nprogress/nprogress.js"></script>
        <!-- bootstrap-progressbar -->
        <script src="/static/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
        <!-- iCheck -->
        <script src="/static/vendors/iCheck/icheck.min.js"></script>
        <!-- bootstrap-daterangepicker -->
        <script src="/static/vendors/moment/min/moment.min.js"></script>
        <script src="/static/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>
        <!-- bootstrap-wysiwyg -->
        <script src="/static/vendors/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js"></script>
        <script src="/static/vendors/jquery.hotkeys/jquery.hotkeys.js"></script>
        <script src="/static/vendors/google-code-prettify/src/prettify.js"></script>
        <!-- jQuery Tags Input -->
        <script src="/static/vendors/jquery.tagsinput/src/jquery.tagsinput.js"></script>
        <!-- Switchery -->
        <script src="/static/vendors/switchery/dist/switchery.min.js"></script>
        <!-- Select2 -->
        <script src="/static/vendors/select2/dist/js/select2.full.min.js"></script>
        <!-- Parsley -->
        <script src="/static/vendors/parsleyjs/dist/parsley.min.js"></script>
        <!-- Autosize -->
        <script src="/static/vendors/autosize/dist/autosize.min.js"></script>
        <!-- jQuery autocomplete -->
        <script src="/static/vendors/devbridge-autocomplete/dist/jquery.autocomplete.min.js"></script>
        <!-- starrr -->
        <script src="/static/vendors/starrr/dist/starrr.js"></script>

      {% endblock %}
      <!-- Custom Theme Scripts -->
      <script src="/static/build/js/custom.js"></script>
    {% endblock body %}

    {% block custom_js %}
    {% endblock custom_js %}

  </body>
</html>

dashboard/templates/dashboard/dashboard_base.html
{% extends "dashboard/base_site.html" %}
{% load humanize %}

{% block title %} Dashboard 1 {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <!-- top tiles -->
    <div class="row tile_count">
      {% for stat in dashboard_top_data%}
      <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
        <span class="count_top"><i class="fa fa-tag"></i> {{ stat.0 }}</span>
        <div class="count">{{ stat.1|intcomma}}</div>

        <span class="count_bottom">
          {% if stat.2 < 0 %}
            <i class="green"><i class="fa fa-sort-desc"></i>{{ stat.2|floatformat:"0"|intcomma }}% </i> from last period
          {% else %}
            <i class="red"><i class="fa fa-sort-asc"></i>{{ stat.2|floatformat:"0"|intcomma }}% </i> from last period
          {% endif %}
        </span>

      </div>
      {% endfor %}

    <!-- /top tiles -->
    {% block charts %}
    {% endblock charts %}
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super}}
  <!-- DateJS -->
  <script src="/static/vendors/DateJS/build/date.js"></script>
  <script src="/static/vendors/echarts/dist/echarts.min.js"></script>
  <!-- Warren Cheng -->
  <script type="text/javascript" src="/static/custom_js/barchart.js"></script>
  <script type="text/javascript" src="/static/custom_js/gauge.js"></script>
  <script type="text/javascript" src="/static/custom_js/heatmap.js"></script>
  <script type="text/javascript" src="/static/custom_js/index.js?v=1.0"></script>
{% endblock javascripts %}

dashboard/templates/dashboard/error_404.html
{% extends "dashboard/base_site.html" %}

{% block title %} Page 404 {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
{% endblock stylesheets %}

{% block sidebar %}{% endblock sidebar %}

{% block top_navigation %}{% endblock top_navigation %}

{% block content %}
  <div class="col-md-12">
    <div class="col-middle">
      <div class="text-center text-center">
        <h1 class="error-number">404</h1>
        <h2>Sorry but we couldn't find this page</h2>
        <p>This page you are looking for does not exist <a href="mailto:warren.cheng@goldfieldsmoney.com.au">Report this?</a>
        </p>
        <div class="mid_center">
          <h4>Click <a href="{% url 'dashboard:index' %}">here</a> to go to the front page.</h4>

        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block footer %}{% endblock footer %}

{% block javascripts %}
  {{ block.super }}
{% endblock javascripts %}

dashboard/templates/dashboard/error_500.html
{% extends "dashboard/base_site.html" %}

{% block title %} Page 500 {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
{% endblock stylesheets %}

{% block sidebar %}{% endblock sidebar %}

{% block top_navigation %}{% endblock top_navigation %}

{% block content %}
  <div class="col-md-12">
    <div class="col-middle">
      <div class="text-center text-center">
        <h1 class="error-number">500</h1>
        <h2>Internal Server Error</h2>
        <p>We track these errors automatically, but if the problem persists feel free to contact us. In the meantime, try refreshing. <a href="mailto:warren.cheng@goldfieldsmoney.com.au">Report this?</a>
        </p>

      </div>
    </div>
  </div>
{% endblock content %}

{% block footer %}{% endblock footer %}

{% block javascripts %}
  {{ block.super }}
{% endblock javascripts %}

dashboard/templates/dashboard/sidebar.html
<div class="left_col scroll-view">
  <div class="navbar nav_title" style="border: 0;">
      <a href="{% url "dashboard:index" %}" class="site_title"><img src="/static/images/bnk.png" style="width:50px;"> </img><span></span></a>
  </div>

  <div class="clearfix"></div>

  <!-- menu profile quick info -->

  <!-- /menu profile quick info -->

  <br />

  <!-- sidebar menu -->
  <div id="sidebar-menu" class="main_menu_side  hidden-print main_menu">
    <div class="menu_section">
      <h3>OP RISK & COMPLIANCE</h3>
      <ul class="nav side-menu">
        <li><a><i class="fa fa-home"></i> Dashboards <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{% url "dashboard:index" %}">Main</a></li>
            <li><a href="{% url "dashboard:incident" %}">Breach & Incident</a></li>
            <li><a href="{% url "dashboard:complaint" %}">Complaint & Dispute</a></li>

          </ul>
        </li>
        <li><a><i class="fa fa-fighter-jet"></i> Risk Factors & Controls <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{% url "forms:addRiskFactor" form_name="risk_factor_add" %}">Add Risk Factor</a></li>
            <li><a href="{% url "forms:display_form" form_name="risk_control" %}">Add Risk Control</a></li>
            <li><a href="{% url "forms:risk_factor_review"  %}">Table View</a></li>





          </ul>
        </li>
        <li><a><i class="fa fa-edit"></i> Forms <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{% url "forms:display_form" form_name="breach_and_incident" %}">Breach & Incident</a></li>
            <li><a href="{% url "forms:display_form" form_name="complaint_and_dispute" %}">Complaint & Dispute</a></li>
            <li><a href="{% url "forms:display_form" form_name="fraud" %}">Fraud</a></li>
            <li><a href="{% url "forms:display_wizard" form_name="hindsight_review" %}">Hindsight Review</a></li>
            <li><a href="{% url "forms:review" %}">Table View</a></li>


          </ul>
        </li>

        <li><a><i class="fa fa-calendar"></i> Compliance Schedule <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{% url "compliance_schedule:addItem" %}">Add Schedule Item</a></li>
            <li><a href="{% url "compliance_schedule:viewCompliance" %}">Table View</a></li>
          </ul>
        </li>
        <li><a><i class="fa fa-bank"></i> Policy Review Schedule <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{% url "compliance_schedule:addPolicy" %}">Add Policy Item</a></li>
            <li><a href="{% url "compliance_schedule:viewPolicy" %}">Table View</a></li>
          </ul>
        </li>

      </ul>
    </div>
    <div class="menu_section">
      <h3>Other Tools</h3>
      <ul class="nav side-menu">
        <li><a><i class="fa fa-bug"></i> Credit <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="e_commerce.html">Volatility</a></li>

          </ul>
        </li>


      </ul>
    </div>
  </div>
  <!-- /sidebar menu -->

  <!-- /menu footer buttons -->
<!--
  <div class="sidebar-footer hidden-small">
    <a data-toggle="tooltip" data-placement="top" title="Settings">
      <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="FullScreen">
      <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Lock">
      <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Logout" href="{% url "logout" %}">
      <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
    </a>
  </div>
-->
  <!-- /menu footer buttons -->
</div>

dashboard/templates/dashboard/top_navigation.html
<div class="nav_menu">
  <nav>
    <div class="nav toggle">
      <a id="menu_toggle"><i class="fa fa-bars"></i></a>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <li class="">
        <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          {{ request.user.first_name }}
          <span class=" fa fa-angle-down"></span>
        </a>
        <ul class="dropdown-menu dropdown-usermenu pull-right">
       
          <li>
            <a href="{% url "password_reset" %}">
              <span>Reset Password</span>
            </a>
          </li>
          <li><a href="mailto:warren.cheng@goldfieldsmoney.com.au">Contact Support</a></li>
          <li><a href="{% url "logout"  %}"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
        </ul>
      </li>

      
    </ul>
  </nav>
</div>