blog/urls.py
from django.urls import path
from django.contrib import admin

from .feeds import LatestPostsFeed
from .import views


app_name = 'blog'
urlpatterns = [
path('feed/',LatestPostsFeed(), name='post_feed'),
path('',views.post_list, name='post_list'),
path('tag/<slug:tag_slug>', views.post_list, name="post_list_by_tag"),
path('<int:post_id>/share/', views.post_share, name='post_share'),
# path('', views.PostListView.as_view(), name='post_list'),
path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail')
]

forms/urls.py
from django.urls import path
from django.contrib import admin
from .import views

app_name = 'forms'
urlpatterns = [

    path('review/', views.SubmissionTableView.as_view(), name='review'),
    path('review/risk_factors', views.RiskFactorTableView.as_view(), name='risk_factor_review'),
    path('review/risk_controls', views.RiskFactorTableView.as_view(), name='risk_control_review'),
    path('submit/<slug:form_name>/',views.DefaultFormView.as_view(), name='display_form'),
    path('submit/<slug:form_name>/wizard/', views.WizardFormView.as_view(), name='display_wizard'),
    path('edit/<slug:form_name>/<int:form_id>/', views.EditFormView.as_view(), name="edit"),
    path('editWizard/<slug:form_name>/<slug:form_id>/', views.EditWizardView.as_view(),name = 'editWizard'),
    path('add/<slug:form_name>/', views.RiskFactorAddView.as_view(), name='addRiskFactor'),
    path('edit_risk_factor/<slug:form_name>/<slug:form_id>/', views.RiskFactorEditView.as_view(), name="editRiskFactor"),

]

forms/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse
from .choices import *


class RiskFactor(models.Model):
    def natural_key(self):
        return self.name
    def __str__(self):
        return "{}".format(self.name)
    BOOLEAN_CHOICES = (
        ('YES','Yes'),
        ('NO','No')
    )
    LIKELIHOOD_CHOICES = (
        ('1. RARE', '1. Rare'),
        ('2. UNLIKELY', '2. Unlikely'),
        ('3. POSSIBLE', '3. Possible'),
        ('4. LIKELY', '4. Likely'),
        ('5. ALMOST CERTAIN', '5. Almost certain')
    )

    POTENTIAL_IMPACT_CHOICES = (
        ('Accounts not recorded correctly in CBS','Accounts not recorded correctly in CBS',),
        ('Breach of regulatory obligations','Breach of regulatory obligations',),
        ('Cost overuns','Cost overuns',),
        ('Credit loss','Credit loss',),
        ('Critical Business Operations (CBOs) not performed','Critical Business Operations (CBOs) not performed',),
        ('Damage to property','Damage to property',),
        ('Declared under FCS','Declared under FCS',),
        ('Delayed strategic outcomes','Delayed strategic outcomes',),
        ('Financial loss through legal action','Financial loss through legal action',),
        ('Inability to meet obligations','Inability to meet obligations',),
        ('Inability to raise further capital','Inability to raise further capital',),
        ('Insurance shortfall','Insurance shortfall',),
        ('Jail','Jail',),
        ('Loss earnings and reduction of capital','Loss earnings and reduction of capital',),
        ('Loss of ADI license','Loss of ADI license',),
        ('Loss of Credit License','Loss of Credit License',),
        ('Loss of customer data','Loss of customer data',),
        ('Loss of customer/deposit confidence','Loss of customer/deposit confidence',),
        ('Loss of customers','Loss of customers',),
        ('Loss of key staff','Loss of key staff',),
        ('Major Disruption','Major Disruption',),
        ('RAS breach','RAS breach',),
        ('Reduced Share Price','Reduced Share Price',),
        ('Regulatory breach','Regulatory breach',),
        ('Regulatory Fine','Regulatory Fine',),
        ('Regulatory investigation','Regulatory investigation',),
        ('Regulatory undertakings/infringement','Regulatory undertakings/infringement',),
        ('Reputational damage','Reputational damage',),
        ('RMF or RMS insufficient','RMF or RMS insufficient',),
        ('Staff injury or fatality','Staff injury or fatality',),
        ('Staff unable to discharge their duties','Staff unable to discharge their duties',),
        ('Temporary or short term operational fault','Temporary or short term operational fault',),

    )
    RISK_CATEGORY_ONE_CHOICES = ((x,x) for x in RISK_CATEGORIES.keys())
    all_level_2_lists = (list(x.keys()) for x in RISK_CATEGORIES.values())
    all_level_3_lists = [list(x.values()) for x in RISK_CATEGORIES.values()]
    all_level_2_risks = [item for sublist in all_level_2_lists for item in sublist]
    all_level_3_risks = [item for sublist in all_level_3_lists for item in sublist]
    all_level_3_risks = [item for sublist in all_level_3_risks for item in sublist]
    RISK_CATEGORY_TWO_CHOICES = ((x,x) for x in all_level_2_risks)
    RISK_CATEGORY_THREE_CHOICES = ((x,x) for x in all_level_3_risks)

    name = models.CharField(max_length =150)
    risk_owner = models.CharField(max_length=200,choices = RISK_OWNER_CHOICES)
    line_of_defense = models.IntegerField()
    risk_category_1 = models.CharField(max_length=150, choices =  RISK_CATEGORY_ONE_CHOICES)
    risk_category_2 = models.CharField(max_length=150, choices =  RISK_CATEGORY_TWO_CHOICES)
    risk_category_3 = models.CharField(max_length=150, choices =  RISK_CATEGORY_THREE_CHOICES)
    operation_risk = models.CharField(
                                max_length=3,
                                choices = BOOLEAN_CHOICES,
                                help_text = "(loss from failed processes, people and systems). APS 115 - include \
                                legal risk but exclude strategic and reputational (eg fraud, vendor, privacy, info security, cyber, DR/BCP)"
                            )
    application = models.CharField(max_length = 100, choices = APPLICATION_CHOICES)
    risk_description = models.TextField()
    material_risk = models.CharField(max_length=3, choices = BOOLEAN_CHOICES)
    RAS_metrics = models.TextField()
    RCSA_category = models.TextField(help_text = "Category of Process involved for Risk & Control self assessment (RCSA)")
    RCSA_process_activity = models.TextField(help_text = "Detailed Process Activities (RCSA)")
    RCSA_objective = models.TextField(help_text = "Objective of the Process (What do we want to achieve - why take the risk) (RCSA)")
    RCSA_inherent_risk = models.TextField(help_text = "Inherent Risks of the processes (RCSA) (Workflow study)")
    # work on getting the options in , and js
    RCSA_potential_impact_1 = models.CharField(choices = POTENTIAL_IMPACT_CHOICES, max_length=100, help_text = "Main potential impact to control -1 (RCSA)")
    RCSA_potential_impact_2 = models.CharField(choices = POTENTIAL_IMPACT_CHOICES, max_length=100, help_text = "Main potential impact to control -2 (RCSA)")
    initial_likelihood = models.CharField(max_length = 30, choices = LIKELIHOOD_CHOICES)
    financial_consequence = models.CharField(max_length=200,choices = CONSEQUENCE_CHOICES)
    reputational_consequence = models.CharField(max_length=200,choices = CONSEQUENCE_CHOICES)
    health_and_safety_consequence = models.CharField(max_length=200,choices = CONSEQUENCE_CHOICES)
    business_continuity_consequence = models.CharField(max_length=200,choices = CONSEQUENCE_CHOICES)
    compliance_and_legal_consequence = models.CharField(max_length=200,choices = CONSEQUENCE_CHOICES)
    initial_risk_rating = models.CharField(max_length = 100, choices = RISK_RATING_CHOICES, blank=True, null=True)
    control_effectiveness = models.IntegerField(default = 0)
    residual_likelihood = models.CharField(max_length = 30, choices = LIKELIHOOD_CHOICES, blank=True)
    residual_risk_rating = models.CharField(max_length = 100, choices = RISK_RATING_CHOICES, blank=True, null=True)
    current_residual_score = models.IntegerField()
    comment = models.TextField(blank=True)

class RiskFactorDelta(models.Model):
    change_date = models.DateTimeField(null = True, blank = True)
    risk_factor = models.ForeignKey(RiskFactor, on_delete= models.CASCADE, related_name = 'deltas')
    residual_risk_rating = models.CharField(max_length = 100, choices = RISK_RATING_CHOICES, blank=True, null=True)
    submitter = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'submitted_risk_factor_deltas')
    reason_for_change = models.TextField(blank=True)
    def __str__(self):
        return "{} {}".format(self.risk_factor, self.change_date)
    class Meta:
        ordering = ('-change_date',)
class RiskControl(models.Model):
    def natural_key(self):
        return self.name
    CATEGORY_ONE_CHOICES = ((x,x) for x in LOSS_EVENT_CATEGORIES.keys())
    all_level_2_lists = (list(x.keys()) for x in LOSS_EVENT_CATEGORIES.values())
    all_level_3_lists = [list(x.values()) for x in LOSS_EVENT_CATEGORIES.values()]
    all_level_2_risks = [item for sublist in all_level_2_lists for item in sublist]
    all_level_3_risks = [item for sublist in all_level_3_lists for item in sublist]
    all_level_3_risks = [item for sublist in all_level_3_risks for item in sublist]
    CATEGORY_TWO_CHOICES = ((x,x) for x in all_level_2_risks)
    CATEGORY_THREE_CHOICES = ((x,x) for x in all_level_3_risks)
    def __str__(self):
        return "{}".format(self.name)
    name = models.CharField(max_length = 200)
    risk_factor = models.ForeignKey(RiskFactor, on_delete= models.CASCADE, related_name = 'risk_controls')
    description = models.TextField()
    control_documents = models.CharField(max_length = 100)
    operational_loss_event_tier_1_category = models.CharField(max_length = 100, help_text="APS115", choices = CATEGORY_ONE_CHOICES)
    operational_loss_event_tier_2_category = models.CharField(max_length = 100, help_text="APS115",  choices = CATEGORY_TWO_CHOICES)
    operational_loss_event_activity = models.CharField(max_length = 100, help_text="APS115",  choices = CATEGORY_THREE_CHOICES)
    test_procedure_for_the_quarter = models.TextField()
    control_score_description = models.TextField()
    control_score = models.IntegerField()
    control_effectiveness = models.IntegerField(help_text = "%")
    potential_treatment_plans = models.TextField()



class Hindsight(models.Model):
    def __str__(self):
        return "loan_account_{}".format(self.loan_account)

    author = models.ForeignKey( User,
                                on_delete = models.CASCADE,
                                related_name = 'submitted_hindisights')
    updater = models.ForeignKey( User,
                                on_delete = models.CASCADE,
                                related_name = 'updated_hindsights')
    completed = models.BooleanField(default = False)
    completion_date = models.DateTimeField(blank = True, null = True)
    updated_date = models.DateTimeField(auto_now = True)
    funder_policy =models.CharField(max_length=200, choices = ADI_CHOICES)
    loan_account = models.CharField(max_length=20)
    borrower_name = models.CharField(max_length = 50)
    loan_approved_by = models.CharField(max_length=50, choices = LOAN_APPROVER_CHOICES)


class Section(models.Model):
    def __str__(self):
        return self.name
    name = models.CharField(max_length=100)

class Question(models.Model):
    ANSWER_TYPE_CHOICES = (
    ('Multiple Choice', "Multiple Choice"),

forms/admin.py
from django.contrib import admin
from .models import Incident, Complaint, Fraud, Hindsight, Question, Answer, Section, RiskFactor, RiskControl, RiskFactorDelta
from rangefilter.filter import DateRangeFilter, DateTimeRangeFilter

admin.site.register(Hindsight)
admin.site.register(Question)
admin.site.register(Answer)
admin.site.register(Section)
@admin.register(RiskFactorDelta)
class RiskFactorDeltaAdmin(admin.ModelAdmin):
    list_display = (
        'risk_factor',
        'submitter',
        'residual_risk_rating',
    )

    ordering = list_display
@admin.register(RiskFactor)
class RiskFactorAdmin(admin.ModelAdmin):
    list_display = (
        'name',
        'risk_category_1',
        'risk_category_2',
        'risk_category_3',
    )
    search_fields = ('name','risk_category_3')
    ordering = list_display
@admin.register(RiskControl)
class RiskControlAdmin(admin.ModelAdmin):
    list_display = (
        'name',
        'risk_factor',
        'operational_loss_event_tier_1_category',
        'operational_loss_event_tier_2_category',
        'control_score',
        'control_effectiveness',

    )
    search_fields = ('name','risk_factor')
    ordering = list_display

@admin.register(Incident)
class IncidentAdmin(admin.ModelAdmin):
    list_filter = (
        ('discovery_date', DateRangeFilter),
        ('submitted_date', DateRangeFilter),
    )
    list_display = (
        'discovery_date',
        'author',
        'updated_date',
        'closed_date',
        'status',
        'risk_owner',
        'root_cause',
        'risk_factor'
    )

    search_fields = ('risk_factor','root_cause')
    raw_id_fields = ('author',)
    data_hierarchy = 'submitted_date'
    ordering = (
        'status',
        'author',
        'risk_owner',
        'submitted_date',
        'updated_date',
        'root_cause',
        'risk_factor'
    )

@admin.register(Complaint)
class ComplaintAdmin(admin.ModelAdmin):
    list_filter = (
        ('discovery_date', DateRangeFilter),
         ('submitted_date', DateRangeFilter),
    )
    list_display = (
        'discovery_date',
        'business_unit',
        'updated_date',
        'closed_date',
        'status',
        'discovery_date',
        'root_cause',
        'risk_factor',
        'broker_name',
        'broker_business_name'
    )
    search_fields = (
        'root_cause',
        'risk_factor',
        'complainant_name',
        'broker_name',
        'broker_business_name'
    )
    raw_id_fields = ('author',)
    data_hierarchy = 'submitted_date'
    ordering = (
        'status',
        'author',
        'submitted_date',
        'updated_date'
    )

@admin.register(Fraud)
class FraudAdmin(admin.ModelAdmin):
    list_display = ('submitted_date', 'author', 'updated_date')
    list_filter = ( 'submitted_date', 'author')
    search_fields = ('result','comment')
    raw_id_fields = ('author',)
    data_hierarchy = 'submitted_date'
    ordering = ('author','submitted_date','updated_date')

forms/apps.py
from django.apps import AppConfig


class FormsConfig(AppConfig):
    name = 'forms'

forms/shell.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse
from forms.models import Incident, Complaint, RiskFactor
# And now, the end is near
# And so I face the final curtain
# My friend, I'll say it clear
# I'll state my case, of which I'm certain
# I've lived a life that's full
# I've traveled each and every highway
# But more, much more than this
# I did it my way
# Regrets, I've had a few
# But then again, too few to mention
# I did what I had to do
# And saw it through without exemption
# I planned each charted course
# Each careful step along the byway
# And more, much more than this
# I did it my way
# Yes, there were times, I'm sure you knew
# When I bit off more than I could chew
# But through it all, when there was doubt
# I ate it up and spit it out
# I faced it all and I stood tall
# And did it my way
# I've loved, I've laughed and cried
# I've had my fill my share of losing
# And now, as tears subside
# I find it all so amusing
# To think I did all that
# And may I say - not in a shy way
# Oh no, oh no, not me
# I did it my way
# For what is a man, what has he got
# If not himself, then he has naught
# To say the things he truly feels
# And not the words of one who kneels
# The record shows I took the blows
# And did it my way
# Yes, it was my way
for c in Complaint.objects.all():
    risk_factor = c.risk_factor
    risk_factor_instance = RiskFactor.objects.get(name = risk_factor)
    c.risk_factor_m = risk_factor_instance
    c.save()

for c in Incident.objects.all():
    risk_factor = c.risk_factor
    risk_factor_instance = RiskFactor.objects.get(name = risk_factor)
    c.risk_factor_m = risk_factor_instance
    c.save()



rating_map = {
'LOW':"1. Low",
"MODERATE":"2. Moderate",
"HIGH": "3. High",
"EXTREME": "4. Extreme",
"NEW":"5. New"
}
from forms.models import RiskFactor
for rf in RiskFactor.objects.all():
    rf.initial_risk_rating = rating_map[rf.initial_risk_rating]
    rf.residual_risk_rating = rating_map[rf.residual_risk_rating]
    rf.previous_residual_risk_rating = rating_map[rf.previous_residual_risk_rating]
    rf.save()

forms/tests.py
from django.test import TestCase

# Create your tests here.

forms/templates/forms/add_risk_factor.html
{% extends "forms/submission.html" %}
{% block custom_js %}

<script>
    var risks = {{ risks|safe }}

    $("#id_risk_category_1").change(function(e){
        var selected = this.value
        var second_level = risks[selected]
        $("#id_risk_category_2 option").remove()
        $("#id_risk_category_2").append("<option value='' selected=''>---------</option>")
        Object.keys(second_level).forEach(function(ele){
            $("#id_risk_category_2").append(`<option value="${ele}">${ele}</option>`)
        })
    })
    $("#id_risk_category_2").change(function(e){
        var level_1 = $("#id_risk_category_1").children("option:selected").val()

        var selected = this.value
        var third_level = risks[level_1][selected]
        $("#id_risk_category_3 option").remove()
        $("#id_risk_category_3").append("<option value='' selected=''>---------</option>")
        third_level.forEach(function(ele){
            $("#id_risk_category_3").append(`<option value="${ele}">${ele}</option>`)
        })
    })
</script>

<script>
  class CalculatedFiller{
    constructor(){
      this.risk_rating = [
        ['1. LOW','1. LOW','1. LOW','2. MODERATE','3. HIGH'],
        ['1. LOW','1. LOW','2. MODERATE','3. HIGH','4. EXTREME'],
        ['1. LOW','2. MODERATE','3. HIGH','4. EXTREME','4. EXTREME',],
        ['2. MODERATE','3. HIGH','3. HIGH','4. EXTREME','4. EXTREME',],
        ['2. MODERATE','3. HIGH','4. EXTREME','4. EXTREME','4. EXTREME',],
      ]
      this.likelihood = [
        '1. RARE',
        '2. UNLIKELY',
        '3. POSSIBLE',
        '4. LIKELY',
        '5. ALMOST CERTAIN',
      ]
    }
    get_max_consequence(){
      var max = 0;
      $("select[id*='consequence']").each(function(i,e){
        var selected = $(e).find("option:selected").val()
        if (selected){
          selected  = parseInt(selected[0])
          max = selected > max?selected:max
        }

      })
      return max;
    }
    fill_initial_risk_rating(){
      try{
        var max_conseq = this.get_max_consequence()
        var initial_likelihood = parseInt($('#id_initial_likelihood :selected').val()[0])
        let initial_risk_rating = this.risk_rating[initial_likelihood-1][max_conseq-1]
        console.log(initial_risk_rating)
        $(`#id_initial_risk_rating option[value="${initial_risk_rating}"]`).prop('selected',true)
      }
      catch (error){
        console.log(error)
      }

    }
    fill_residual_likelihood(){
      try {
        let control_effectiveness = parseInt($("#id_control_effectiveness").val())/100
        var initial_likelihood = parseInt($('#id_initial_likelihood :selected').val()[0])
        var residual_likelihood = Math.max(Math.round((1-control_effectiveness)*initial_likelihood,0),1)
        console.log(`residual_likelihood=${residual_likelihood}`)
        $(`#id_residual_likelihood option[value="${this.likelihood[residual_likelihood-1]}"]`).prop('selected',true)

      }
      catch (error){
        console.log(error)
      }

    }
    fill_residual_risk_rating(){
      try {
        let residual_likelihood = parseInt($('#id_residual_likelihood :selected').val()[0])
        let max_conseq = this.get_max_consequence()
        let residual_risk_rating = this.risk_rating[residual_likelihood-1][max_conseq-1]
        $(`#id_residual_risk_rating option[value="${residual_risk_rating}"]`).prop('selected',true)
        if (residual_risk_rating != $('#id_previous_residual_risk_rating').val()){
          $('#id_reason_for_change').attr('disabled',false)
        } else {
          $('#id_reason_for_change').attr('disabled',true)
        }

      }
      catch (error){
        console.log(error)
      }


    }
    fill_residual_score(){
      try{
        let residual_likelihood = parseInt($('#id_residual_likelihood :selected').val()[0])
        let max_conseq = this.get_max_consequence()
        $("#id_current_residual_score").val(max_conseq * residual_likelihood)

      }
      catch(error){
        console.log(error)
      }

    }
    fill_line_of_defense(){
      try{
        if ( $("#id_risk_owner").val() == "Chief Risk Officer"){
          $("#id_line_of_defense").val(2)
        } else {
          $("#id_line_of_defense").val(1)
        }


      } catch (error){
        console.log(error)
      }


    }

  }
  $(document).ready(function(){
    if( $('#title').text().includes('Risk Factor')){
      console.log("run!!")
      filler = new CalculatedFiller()
      $("#target-form").change(function(){
        console.log('change')
        filler.fill_initial_risk_rating()
        filler.fill_residual_likelihood()
        filler.fill_residual_risk_rating()
        filler.fill_residual_score()
        filler.fill_line_of_defense()
      })


    } else {
      console.log('not risk factor')
    }
  }
)

</script>
{% endblock %}

forms/templates/forms/edit.html
{% extends "forms/submission.html" %}

{% block action %}
Revision
{% endblock %}

{% block submit_button %}
<button type="submit" class="btn btn-success">Update</button>
{% endblock %}

forms/templates/forms/submission.html
{% extends "dashboard/base_site.html" %}
{% load widget_tweaks %}
{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>BNK Reporting Form</h3>
        </div>


      </div>
      <div class="clearfix"></div>
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2 id='title'>{{ form_name }} {% block action %}Submission{% endblock %}</h2>
              <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            {% if submitted %}
              <div class="x_content">
                  <p>The form has been submitted successfully!</p>
              </div>
            {% else %}
            <div class="x_content">
              <small>FIELDS WITH A STAR (*) ARE REQUIRED</small>
              <br />
              <form id="target-form" action="." method="POST" data-parsley-validate class="form-horizontal form-label-left">

                {% for field in form %}

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">{{ field.label }}
                      {% if field.field.required %}
                      <span class="required">*</span>
                      {% endif %}
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                         {% render_field field class+="form-control col-md-7 col-xs-12" placeholder=field.help_text %}

                    </div>
                    {{ field.errors }}
                </div>

                {% endfor %}
                {% csrf_token %}

                <div class="ln_solid"></div>
                <div class="form-group">
                  <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                    {% block submit_button %}

  		              <button class="btn btn-primary" type="reset">Reset</button>
                    <button type="submit" class="btn btn-success">Submit</button>

                    {% endblock %}
                  </div>
                </div>

              </form>
            </div>
            {% endif %}
          </div>
        </div>
      </div>

    </div>
  </div>
  <div id = 'consequence' class="modal fade " tabindex="-1" role="dialog" aria-hidden="true" style="display: none; ">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
          </button>
          <h4 class="modal-title" id="myModalLabel2">Consequence Matrix</h4>
        </div>
        <div class="modal-body">
          <img src ="/static/images/consequence_1.png" style="width:100%;"></img>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

        </div>

      </div>
    </div>
  </div>
  <div id = 'likelihood' class="modal fade " tabindex="-1" role="dialog" aria-hidden="true" style="display: none; ">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
          </button>
          <h4 class="modal-title" id="myModalLabel3">Likelihood Definition</h4>
        </div>
        <div class="modal-body">
          <img src ="/static/images/likelihood.png" style="width:100%;"></img>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

        </div>

      </div>
    </div>
  </div>

{% endblock content %}
{% block custom_js%}

<script>
  $.expr[":"].contains = $.expr.createPseudo(function(arg) {
    return function( elem ) {
        return $(elem).text().toUpperCase().indexOf(arg.toUpperCase()) >= 0;
      };
  });
  $("label:contains('Consequence')").append(`<small><a style='color:red; cursor:pointer' data-toggle='modal' data-target='#consequence'>(?)</a></small>`)
  $("label:contains('likelihood')").append(`<small><a style='color:red; cursor:pointer' data-toggle='modal' data-target='#likelihood'>(?)</a></small>`)



</script>
<script>
  var loss_event_categories =  {{ loss_event_categories|safe }}
  $("#id_operational_loss_event_tier_1_category").change(function(e){
      var selected = this.value
      var second_level = loss_event_categories[selected]
      $("#id_operational_loss_event_tier_2_category option").remove()
      $("#id_operational_loss_event_tier_2_category").append("<option value='' selected=''>---------</option>")
      Object.keys(second_level).forEach(function(ele){
          $("#id_operational_loss_event_tier_2_category").append(`<option value="${ele}">${ele}</option>`)
      })
  })
  $("#id_operational_loss_event_tier_2_category").change(function(e){
      var level_1 = $("#id_operational_loss_event_tier_1_category").children("option:selected").val()

      var selected = this.value
      var third_level = loss_event_categories[level_1][selected]
      $("#id_operational_loss_event_activity option").remove()
      $("#id_operational_loss_event_activity").append("<option value='' selected=''>---------</option>")
      third_level.forEach(function(ele){
          $("#id_operational_loss_event_activity").append(`<option value="${ele}">${ele}</option>`)
      })
  })
</script>
{% endblock custom_js%}

forms/templates/forms/table_risk_factors.html
{% extends "forms/table_base.html" %}
{% load humanize %}
{% load maxConseq %}
{% load prettyHeader %}
{% block table_title %}
Risk Factors
{% endblock%}
{% block tables %}

<div class="row">
  {% for table in data %}
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2> {{ table.name }} </h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <table id="{{ table.id }}" class="table table-striped table-bordered" width="100%">
          <thead>
            <tr>

                {% for field, value in table.data.0.fields.items %}
                  <th class="{{ field }}">{{ field|prettyHeader }}</th>
                  {% endfor %}
                  {% if table.name == "Risk Factor" %}
                  <th class="max_consequence">Max Conseq</th>
                  {% endif %}
                  <th class="action">Action</th>
            </tr>
          </thead>
          <tbody>
            {% for instance in table.data %}
              <tr>
                {% for field, value in instance.fields.items %}
                  {% if "date" in field %}
                    <td>{{ value|date:"Y-m-d"}}</td>
                  {% elif "amount" in field or "loss" in field %}
                    <td>{{ value|floatformat:"0"|intcomma }}</td>
                  {% else %}
                    <td>{{value|title}} </td>
                  {% endif %}
                {% endfor %}
                {% if table.name == "Risk Factor" %}
                <td>{{ instance.pk|maxConseq}}</td>
                {% endif %}


                <td><a href="{% url "forms:editRiskFactor" form_name=table.id form_id=instance.pk %}"><strong>Edit</strong></a></td>

              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
  {% endfor %}


</div>

{% endblock %}